name: Checks

on:
  push

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: volta-cli/action@v4
      - run: yarn install
      - run: yarn fmt:check
      - run: yarn lint
      - run: yarn test
