name: Checks

on:
  push

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v4
      - run: npm install
      - run: npm run format
      - run: npm run lint
